apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-crud
  name: quarkus-crud
spec:
  replicas: 14
  selector:
    matchLabels:
      deployment: quarkus-crud
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: quarkus-crud
    spec:
      containers:
      - env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: db-configs
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              key: user
              name: db-configs
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: database
              name: db-configs
        image: registry.redhat.io/rhel8/postgresql-12:latest
        name: postgresql-12
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: 500m
      - env:
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: db-configs
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: user
              name: db-configs
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: database
              name: db-configs
        image: quay.io/vsantoma/quarkus-crud:latest
        imagePullPolicy: IfNotPresent
        name: quarkus-crud
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: 1500m
        ports:
        - containerPort: 8080
          protocol: TCP