apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-compute-simulation
  name: quarkus-compute-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: quarkus-compute-simulation
  template:
    metadata:
      labels:
        deployment: quarkus-compute-simulation
    spec:
      containers:
      - image: quay.io/vsantoma/jmeter:latest
        name: quarkus-compute-simulation
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: 250m
        volumeMounts:
        - mountPath: /inputs
          name: jmeter-volume-1
      volumes:
      - configMap:
          defaultMode: 420
          name: quarkus-compute-simulation
        name: jmeter-volume-1