apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jboss-crud-simulation
  name: jboss-crud-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: jboss-crud-simulation
  template:
    metadata:
      labels:
        deployment: jboss-crud-simulation
    spec:
      initContainers:
      - name: init-simulation
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup jboss-crud; do echo waiting for jboss-crud to be up; sleep 2; done"]
      containers:
      - image: quay.io/vsantoma/jmeter:latest
        name: jmeter
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: 250m
        volumeMounts:
        - mountPath: /inputs
          name: jmeter-volume-1
      volumes:
      - configMap:
          defaultMode: 420
          name: jboss-crud-simulation
        name: jmeter-volume-1