apiVersion: 1

datasources:
  - name: Prometheus - Quarkus
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    access: proxy
    basicAuth: false
    withCredentials: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
    #please note you have to replace the token from 
      httpHeaderValue1: "Bearer {token}"
      editable: true
