apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-compute
  name: quarkus-compute
spec:
  replicas: 40
  selector:
    matchLabels:
      deployment: quarkus-compute
  template:
    metadata:
      labels:
        deployment: quarkus-compute
    spec:
      containers:
      - image: quay.io/vsantoma/quarkus-compute:latest
        name: quarkus-compute
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: 2500m